### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by ngmisl** [catppuccin/tabby#1]
hey, anyone got an example?

I don't have a .terminal.customColorSchemes[] in my config

**Comment by nekowinston** [comment]
I've never used Tabby, but I'd assume normal YAML syntax?
```yaml
terminal:
  customColorSchemes:
  - name: Catppuccin Mocha
    foreground: HSL(226, 64%, 88%)
    background: HSL(240, 21%, 15%)
    selection: null
    cursor: HSL(10, 56%, 91%)
    cursorAccent: null
    colors:
      - HSL(234, 13%, 31%)
      - HSL(343, 81%, 75%)
      - HSL(115, 54%, 76%)
      - HSL(41, 86%, 83%)
      - HSL(217, 92%, 76%)
      - HSL(316, 72%, 86%)
      - HSL(189, 71%, 73%)
      - HSL(226, 64%, 88%)
      - HSL(234, 13%, 36%)
      - HSL(343, 81%, 80%)
      - HSL(115, 54%, 81%)
      - HSL(41, 86%, 88%)
      - HSL(217, 92%, 81%)
      - HSL(316, 72%, 91%)
      - HSL(189, 71%, 78%)
      - HSL(226, 64%, 93%)
```

**Comment by ngmisl** [comment]
i have it like this:

`  customColorSchemes:
    - name: Catppuccin Mocha
      foreground: HSL(226, 64%, 88%)
      background: HSL(240, 21%, 15%)
      selection: null
      cursor: HSL(10, 56%, 91%)
      cursorAccent: null
      colors:
        - HSL(234, 13%, 31%)
        - HSL(343, 81%, 75%)
        - HSL(115, 54%, 76%)
        - HSL(41, 86%, 83%)
        - HSL(217, 92%, 76%)
        - HSL(316, 72%, 86%)
        - HSL(189, 71%, 73%)
        - HSL(226, 64%, 88%)
        - HSL(234, 13%, 36%)
        - HSL(343, 81%, 80%)
        - HSL(115, 54%, 81%)
        - HSL(41, 86%, 88%)
        - HSL(217, 92%, 81%)
        - HSL(316, 72%, 91%)
        - HSL(189, 71%, 78%)
        - HSL(226, 64%, 93%)`
but tabby always overwrites this, it won't let me select this theme

**Comment by manujarvinen** [comment]
For those people that don't know YAML structure and can't understand the brief instructions in the main page on how to make this work:

It seems the indentations need to be _exact_ and yes, there needs to be the line in there that was mentioned here in the second post. And take out the brackets []. Phew.

So, like this (for Frappé):

```
  customColorSchemes:
    - name: Catppuccin Frappé
      foreground: '#c6d0f5'
      background: '#303446'
      selection: null
      cursor: '#f2d5cf'
      cursorAccent: null
      colors:
        - '#51576d'
        - '#e78284'
        - '#a6d189'
        - '#e5c890'
        - '#8caaee'
        - '#f4b8e4'
        - '#81c8be'
        - '#b5bfe2'
        - '#51576d'
        - '#e78284'
        - '#a6d189'
        - '#e5c890'
        - '#8caaee'
        - '#f4b8e4'
        - '#81c8be'
        - '#a5adce'
```
